implementing the copy contructors for two helper classes because compiler on macos seems to have a different implementation of stl::find which needs the copy constructor. Other implementations avoid this
Solves compilation error
***** Compiling HLT/BASE/AliHLTComponent.cxx *****
HLT/BASE/AliHLTComponent.cxx: In member function ‘int AliHLTComponent::ProcessEvent(const AliHLTComponentEventData&, const AliHLTComponentBlockData*, AliHLTComponentTriggerData&, AliHLTUInt8_t*, AliHLTUInt32_t&, AliHLTUInt32_t&, AliHLTComponentBlockData*&, AliHLTComponentEventDoneData*&)’:
HLT/BASE/AliHLTComponent.cxx:1733: error: ‘<unnamed>::AliHLTComponentStatisticsId::AliHLTComponentStatisticsId(const<unnamed>::AliHLTComponentStatisticsId&)’ is private
HLT/BASE/AliHLTComponent.cxx:1899: error: within this context
HLT/BASE/AliHLTComponent.cxx:1755: error: ‘<unnamed>::AliHLTComponentBlockDataSpecification::AliHLTComponentBlockDataSpecification(const<unnamed>::AliHLTComponentBlockDataSpecification&)’ is private
HLT/BASE/AliHLTComponent.cxx:1906: error: within this context
make[1]: *** [HLT/tgt_macosx64/BASE/AliHLTComponent.o] Error 1
make: *** [default] Error 2